module: src.client.agents.HTTPAgent
parameters:
  url: https://api.openai.com/v1/chat/completions
  proxies: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
  headers:
    Content-Type: application/json
    Authorization: Bearer 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
  body:
    temperature: 0.1
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[choices][0][message][content]}"
